FROM node:10.15.3-alpine

RUN apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python bash ca-certificates

ARG NODE_ENV=development
ENV NODE_ENV $NODE_ENV

WORKDIR /usr/src/app
COPY . .

RUN yarn install

EXPOSE 5000
CMD [ "yarn", "start" ]
